runtime: python39
instance_class: F1

env_variables:
  TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
  TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
  TWILIO_FROM_NUMBER: ${TWILIO_FROM_NUMBER}
  NOTIFICATION_TO_NUMBER: ${NOTIFICATION_TO_NUMBER}
  MIN_PROFIT_THRESHOLD: "1.05"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 3

handlers:
- url: /.*
  script: auto 